# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonsList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'SwiftyJSON', '~> 3.0'
    pod 'Alamofire', '~> 4.0'
  # Pods for PersonsList

  target 'PersonsListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PersonsListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
